# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/deniz/lab_5_2/lab_5_2.cache/wt [current_project]
set_property parent.project_path /home/deniz/lab_5_2/lab_5_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/deniz/lab_5_2/lab_5_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  /home/deniz/lab_5_2/lab_5_2.srcs/sources_1/new/DFF.sv
  /home/deniz/lab_5_2/lab_5_2.srcs/sources_1/new/SR8bx2wA.sv
  /home/deniz/lab_5_2/lab_5_2.srcs/sources_1/new/SR8b.sv
  /home/deniz/lab_5_2/lab_5_2.srcs/sources_1/new/Clock.sv
  /home/deniz/lab_5_2/lab_5_2.srcs/sources_1/new/SR8A.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/deniz/lab_5_2/lab_5_2.srcs/constrs_1/new/SR8A.xdc
set_property used_in_implementation false [get_files /home/deniz/lab_5_2/lab_5_2.srcs/constrs_1/new/SR8A.xdc]


synth_design -top SR8A -part xc7a35tcpg236-1


write_checkpoint -force -noxdef SR8A.dcp

catch { report_utilization -file SR8A_utilization_synth.rpt -pb SR8A_utilization_synth.pb }
