# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/deniz/lab_2/lab_2.cache/wt [current_project]
set_property parent.project_path /home/deniz/lab_2/lab_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/deniz/lab_2/lab_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  /home/deniz/lab_2/lab_2.srcs/sources_1/new/Half_Subtractor_Behavioral.sv
  /home/deniz/lab_2/lab_2.srcs/sources_1/new/Half_Adder_Behavioral.sv
  /home/deniz/lab_2/lab_2.srcs/sources_1/new/Lab_Calculator_Structural.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/deniz/lab_2/lab_2.srcs/constrs_1/new/Two_Bit_Adder_Structural.xdc
set_property used_in_implementation false [get_files /home/deniz/lab_2/lab_2.srcs/constrs_1/new/Two_Bit_Adder_Structural.xdc]

read_xdc /home/deniz/lab_2/lab_2.srcs/constrs_1/new/Lab_Calculator_Structural.xdc
set_property used_in_implementation false [get_files /home/deniz/lab_2/lab_2.srcs/constrs_1/new/Lab_Calculator_Structural.xdc]


synth_design -top Lab_Calculator_Structural -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Lab_Calculator_Structural.dcp

catch { report_utilization -file Lab_Calculator_Structural_utilization_synth.rpt -pb Lab_Calculator_Structural_utilization_synth.pb }
